spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: recokr
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console


  sql:
    init:
      schema-locations: classpath:query/schema.sql
      data-locations: classpath:query/data.sql
      mode: always


---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    generate-ddl: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
  sql:
    init:
      schema-locations: classpath:query/schema.sql
      data-locations: classpath:query/data.sql
      mode: always

---
spring:
  profiles:
    group:
      "dev": "test,local"